Switch to setup-node@v2 for better caching.
rocicorp/replicache pull request #523
Opened 2021-09-16 16:38 UTC by whiten

2021-09-17 21:44 UTC, arv commented
It is a lot cleaner so LGTM

It does not seem to impact the time much thogh

2021-09-23 06:25 UTC, arv commented
Are you still working on this one?

2021-10-14 22:22 UTC, arv requested changes

2021-10-14 22:22 UTC, arv commented on .github/workflows/js.yml
> +      - run: npx playwright install-deps chromium
That does not seem right. We run the tests on Firefox and WebKit too

2021-10-14 23:13 UTC, whiten commented on .github/workflows/js.yml
> +      - run: npx playwright install-deps chromium
Yeah, I mixed this up with perf tests, where we default to only chromium.

2021-10-14 23:17 UTC, merged